# .github/workflows/mock-secret-workflow.yml
name: Mock Secret Workflow

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      
      - run: unzip pr.zip

      - name: Generate response with secret
        run: |
          PR_TITLE=$(cat title.txt)
          echo "Response for PR: $PR_TITLE using secret: ${{ secrets.MOCK_SECRET }}" > response.txt
          cat response.txt
